### PR TITLE
WIP: Use versioned_client

### PR DESCRIPTION
**Pull request by wallrj**
My attempt to have kubetop use versioned client from https://github.com/LeastAuthority/txkube/pull/130

Unfortunately I still get the original error:

```
(kubetop) [richard@drax kubetop]$ kubetop 
Traceback (most recent call last):
Failure: twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#1, [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'schedulerName' are not among the specified fields for io.k8s.kubernetes.pkg.api.v1.PodSpec
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/twisted/web/_newclient.py:1185:_bodyDataFinished_CONNECTED
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/twisted/web/client.py:2115:connectionLost
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/twisted/internet/defer.py:457:callback
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/twisted/internet/defer.py:565:_startRunCallbacks
--- <exception caught here> ---
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/twisted/internet/defer.py:651:_runCallbacks
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/eliot/twisted.py:82:callbackWithContext
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/eliot/_action.py:389:run
/home/richard/projects/LeastAuthority/txkube/src/txkube/_network.py:295:<lambda>
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/pyrsistent/_helpers.py:80:inner_f
/home/richard/projects/LeastAuthority/txkube/src/txkube/_model.py:85:iobject_from_raw
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/pyrsistent/_pclass.py:113:create
/home/richard/projects/LeastAuthority/txkube/src/txkube/_model.py:263:__new__
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/pyrsistent/_pclass.py:52:__new__
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/pyrsistent/_checked_types.py:200:_checked_type_create
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/pyrsistent/_pclass.py:113:create
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/pyrsistent/_pclass.py:52:__new__
/home/richard/projects/LeastAuthority/txkube/src/txkube/_swagger.py:265:optional
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/pyrsistent/_pclass.py:113:create
/home/richard/.virtualenvs/kubetop/lib/python2.7/site-packages/pyrsistent/_pclass.py:67:__new__
]]
]]

```

And I can't find any reference to `schedulerName` in the kubetop code (yet).

### CODE REVIEW

**Comment by wallrj** [comment]
Some version information:

```
(kubetop) [richard@drax txkube]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-05-09T23:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```


```
(kubetop) [richard@drax txkube]$ minikube version
minikube version: v0.19.0
```

And schedulerName only seems to be mentioned in the 1.7 spec.

```
(kubetop) [richard@drax txkube]$ git grep schedulerName
src/txkube/kubernetes-1.7.json:     "schedulerName": {
```

**Comment by exarkun** [comment]
With the latest txkube branch (https://github.com/LeastAuthority/txkube/pull/132) this now fails differently:

```
Traceback (most recent call last):
Failure: twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.KeyError'>: u'items'
/home/exarkun/Environments/kubetop/local/lib/python2.7/site-packages/twisted/internet/defer.py:651:_runCallbacks
/home/exarkun/Environments/kubetop/local/lib/python2.7/site-packages/twisted/internet/defer.py:1030:_cbDeferred
/home/exarkun/Environments/kubetop/local/lib/python2.7/site-packages/twisted/internet/defer.py:457:callback
/home/exarkun/Environments/kubetop/local/lib/python2.7/site-packages/twisted/internet/defer.py:565:_startRunCallbacks
--- <exception caught here> ---
/home/exarkun/Environments/kubetop/local/lib/python2.7/site-packages/twisted/internet/defer.py:651:_runCallbacks
/home/exarkun/Work/LeastAuthority/kubetop/src/kubetop/_topdata.py:98:combine
]]
]]
```

It looks like the Heapster endpoints have been moved around.

Notably, against Kubernetes 1.7 alpha whatever, `kubectl top ...` fails with what is apparently the same error.

**Comment by exarkun** [comment]
The problem now seems unrelated to txkube.  Instead, the issue is that the Heapster APIs no longer work the same way in 1.6 (and 1.7).  However, I have been unable to determine how they _do_ work...

**Comment by exarkun** [comment]
On 1.6 (and I would suppose earlier versions as well) the Heapster API (https://github.com/kubernetes/heapster/blob/master/docs/model.md) is accessible on the Heapster pod's port 8082... not published publically by default though (so, eg, you have to set up a port forward to get there).

**Comment by exarkun** [comment]
It ... looks a bit like ... Heapster removed the APIs Kubetop was based on.

**Comment by mithrandi** [comment]
With some unrelated txkube hackery to make authentication work for my GKE cluster, this PR works against my 1.6.6 GKE cluster.

**Comment by exarkun** [comment]
This now seems to be working against k8s 1.6.3.  It's still not working on my 1.6.7 cluster but that one appears not to have Heapster installed at all ...

**Pull request merged**
